### ISSUE TITLE
在Java中什么是线程调度？

### ISSUE THREAD

**Issue by butAlso** [Homiss/Java-interview-questions#1]
你的：
 JVM调度的模式有两种：分时调度和抢占式调度。  分时调度是所有线程轮流获得CPU使用权，并平均分配每个线程占用CPU的时间;  抢占式调度是根据线程的优先级别来获取CPU的使用权。  JVM的线程调度模式采用了抢占式模式。既然是抢占调度，那么我们就能通过设置优先级来“有限”的控制线程的运行顺序，注意“有限”一次。

深入理解java虚拟机里写道：jvm调度方式包括协同式和抢占式，你的分时调度，不就是抢占式的实现方法吗？

**Comment by Homiss** [comment]
嗯嗯，谢谢指出错误。
